Adding CF Manifests For Other Regions
aquasecurity/saas-aws-control-tower pull request #3
Opened 2023-02-23 12:02 UTC by sm171190

In this change we have added stacksets for EU, Asia-1 and Asia-2 regions. For each of the manifests we have provided the corresponding aqua_url, SourceIP and ARNs

2023-02-23 12:03 UTC, sm171190 commented
@giorod3 Please review . Thanks

2023-02-27 14:57 UTC, giorod3 approved these changes

2023-02-27 14:58 UTC, giorod3 requested changes
i think changing the name without updating other places might break functionality?

2023-03-01 11:37 UTC, giorod3 approved these changes

2023-03-01 11:37 UTC, merged